// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90okqdRtHwHzncoN3S_o5mcLDYDuBUwM',
    appId: '1:700456212189:web:a924f979e03f2c8f746d34',
    messagingSenderId: '700456212189',
    projectId: 'ultimate-marketplace-f16c9',
    authDomain: 'ultimate-marketplace-f16c9.firebaseapp.com',
    storageBucket: 'ultimate-marketplace-f16c9.firebasestorage.app',
    measurementId: 'G-N5MVS4FBTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8zFCll7zBF6VlISNCzeFBJeX2iVlk1I',
    appId: '1:700456212189:android:55b180090100ae4a746d34',
    messagingSenderId: '700456212189',
    projectId: 'ultimate-marketplace-f16c9',
    storageBucket: 'ultimate-marketplace-f16c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHRJSh8IM3QOBf5IwCM_367ciNq3u9hg',
    appId: '1:700456212189:ios:c562c6510f255466746d34',
    messagingSenderId: '700456212189',
    projectId: 'ultimate-marketplace-f16c9',
    storageBucket: 'ultimate-marketplace-f16c9.firebasestorage.app',
    iosBundleId: 'com.example.carsKg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfHRJSh8IM3QOBf5IwCM_367ciNq3u9hg',
    appId: '1:700456212189:ios:c562c6510f255466746d34',
    messagingSenderId: '700456212189',
    projectId: 'ultimate-marketplace-f16c9',
    storageBucket: 'ultimate-marketplace-f16c9.firebasestorage.app',
    iosBundleId: 'com.example.carsKg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA90okqdRtHwHzncoN3S_o5mcLDYDuBUwM',
    appId: '1:700456212189:web:582edc87f1e551a3746d34',
    messagingSenderId: '700456212189',
    projectId: 'ultimate-marketplace-f16c9',
    authDomain: 'ultimate-marketplace-f16c9.firebaseapp.com',
    storageBucket: 'ultimate-marketplace-f16c9.firebasestorage.app',
    measurementId: 'G-7SMVPC8ME8',
  );
}
